---
- hosts: jellyfish
  user: root

  roles:
    - role: geekoops-nginx
      vars:
        config_firewall: true
        firewall_zone: "public"
    - role: geekoops-php-fpm
      vars:
        apcu_enable: true
        apcu_shm_size: 32M
        php_memlimit: 256M
        php_maxuploadsize: 64M

    tasks:
    - name: Deploy jellyfish config for nginx
      copy:
        content: |
          server {
            listen 80 default_server;
            listen [::]:80 default_server;
            server_name jellyfish;
            location / {
              proxy_pass http://127.0.0.1:3000/;
            }
          }
        dest: "/etc/nginx/vhosts.d/jellyfish.conf"
        group: "root"
        owner: "root"
        mode: 0754
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
